bt_navigator:
  ros__parameters:
    global_frame: odom  # Use odom as reference
    robot_base_frame: base_link
planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      max_vel_x: 0.3
      min_vel_x: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      acc_lim_x: 1.0
      acc_lim_theta: 2.0
      decel_factor: 1.0
