bt_navigator:
  ros__parameters:
    global_frame: odom  # Use odom as reference
    robot_base_frame: base_link
planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
